name: 'Scan for API Specifications'
description: 'Scan Github for API specifications'
inputs:
  who-to-greet:  # id of input
    description: 'Trying to scan private repositories in an organization'
    required: true
    default: 'World'
  stoplight-api-key:
    description: 'The Stoplight API key'
    required: true
  stoplight-project-id: 
    description : 'An external project identifier for this publication. Useful to distinguish between internal and external docs'
    required : false
    default : '30213'
outputs:
  time: # id of output
    description: 'when we finished the scanning'
runs:
  using: 'node12'
  main: 'index.js'