name: 'Scan for API Specifications'
description: 'Scan Github for API specifications'
inputs:
  who-to-greet:  # id of input
    description: 'Trying to scan private repositories in an organization'
    required: true
    default: 'World'
  stoplight-api-key:
    description: 'The Stoplight API key'
    required: true
outputs:
  time: # id of output
    description: 'The list of repositories we found'
runs:
  using: 'node12'
  main: 'index.js'