name: Scan Repositories for API Specifications
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to scan Github repositories for APi Specifications.  These are repositories with api-spec-metadata.yml
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change to where we have defined package.json and download node dependencies
        run : |
          cd ./.github/actions/repository-api-spec-harvester 
          npm install 
          echo "currently in" $PWD
          ls -a

      - name: Scan Github Repositories
        uses: ./.github/actions/repository-api-spec-harvester # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: "Jason Stratham"
          stoplight-api-key:  ${{ secrets.STOPLIGHT_API_KEY }}
          stoplight-project-id: '30213'
      # Use the output from the `hello` step
      - name: List the repositories we found with API specifications
        run: echo "The time was ${{ steps.hello.outputs.time }}"